// Mock product catalog shared by Collection / Product Detail / Cart / Checkout.
// Images reference the placeholder gradient classes defined in css/style.css
// (.ph-1 / .ph-2 / .ph-3) so real assets can drop in later without markup changes.
window.TACET_PRODUCTS = [
  {
    id: 'p01',
    name: 'ウールメルトン ロングコート',
    category: 'Outerwear',
    price: 68000,
    description: '上質なウールメルトン素材を用いた、シルエットにこだわったロングコート。',
    colors: ['Black', 'Greige'],
    sizes: ['S', 'M', 'L'],
    images: ['ph-1', 'ph-2'],
  },
  {
    id: 'p02',
    name: 'カシミヤブレンド チェスターコート',
    category: 'Outerwear',
    price: 98000,
    description: 'カシミヤを配合した柔らかな風合いの、上品な佇まいのチェスターコート。',
    colors: ['Black', 'Camel'],
    sizes: ['S', 'M', 'L'],
    images: ['ph-2', 'ph-3'],
  },
  {
    id: 'p03',
    name: 'ステンカラーコート',
    category: 'Outerwear',
    price: 52000,
    description: '軽やかな着心地とすっきりとした襟元が特徴の、通年で使えるステンカラーコート。',
    colors: ['Greige', 'Black'],
    sizes: ['S', 'M', 'L'],
    images: ['ph-1', 'ph-3'],
  },
  {
    id: 'p04',
    name: 'ノーカラーウールジャケット',
    category: 'Outerwear',
    price: 46000,
    description: '襟元をなくしミニマルに仕上げた、羽織るだけで様になるウールジャケット。',
    colors: ['Black'],
    sizes: ['S', 'M', 'L'],
    images: ['ph-2', 'ph-1'],
  },
  {
    id: 'p05',
    name: 'シルクブレンド ブラウス',
    category: 'Tops',
    price: 28000,
    description: 'シルクを混紡した上品な光沢感が特徴の、体のラインを拾わないブラウス。',
    colors: ['Ivory', 'Black'],
    sizes: ['S', 'M', 'L'],
    images: ['ph-1', 'ph-2'],
  },
  {
    id: 'p06',
    name: 'コットンリネン シャツ',
    category: 'Tops',
    price: 24000,
    description: 'コットンとリネンの混紡素材による、自然な涼感とハリ感を両立したシャツ。',
    colors: ['White', 'Greige'],
    sizes: ['S', 'M', 'L'],
    images: ['ph-3', 'ph-1'],
  },
  {
    id: 'p07',
    name: 'ハイゲージ ニットプルオーバー',
    category: 'Tops',
    price: 32000,
    description: '細番手の糸を用いた上質な編地の、レイヤードにも映えるプルオーバー。',
    colors: ['Black', 'Ivory'],
    sizes: ['S', 'M', 'L'],
    images: ['ph-2', 'ph-3'],
  },
  {
    id: 'p08',
    name: 'タートルネック カットソー',
    category: 'Tops',
    price: 19000,
    description: '肌当たりの良いコットン素材を使用した、単体でもレイヤードでも活躍するカットソー。',
    colors: ['Black', 'Greige', 'Ivory'],
    sizes: ['S', 'M', 'L'],
    images: ['ph-1', 'ph-3'],
  },
  {
    id: 'p09',
    name: 'テーパード ウールトラウザー',
    category: 'Bottoms',
    price: 38000,
    description: '裾に向けて緩やかに絞ったシルエットの、上質なウール素材のトラウザー。',
    colors: ['Black', 'Greige'],
    sizes: ['S', 'M', 'L'],
    images: ['ph-2', 'ph-1'],
  },
  {
    id: 'p10',
    name: 'ワイドシルエット スラックス',
    category: 'Bottoms',
    price: 34000,
    description: 'ゆとりのあるワイドシルエットが特徴の、きれいめにもカジュアルにも合わせやすいスラックス。',
    colors: ['Black'],
    sizes: ['S', 'M', 'L'],
    images: ['ph-3', 'ph-2'],
  },
  {
    id: 'p11',
    name: 'ストレートデニム',
    category: 'Bottoms',
    price: 22000,
    description: 'クラシックなストレートシルエットの、着るほどに馴染むリジッドデニム。',
    colors: ['Indigo', 'Black'],
    sizes: ['S', 'M', 'L'],
    images: ['ph-1', 'ph-2'],
  },
  {
    id: 'p12',
    name: 'タックプリーツスカート',
    category: 'Bottoms',
    price: 30000,
    description: '細やかなタックプリーツが上品な陰影を生む、Aラインのロングスカート。',
    colors: ['Black', 'Greige'],
    sizes: ['S', 'M', 'L'],
    images: ['ph-2', 'ph-1'],
  },
  {
    id: 'p13',
    name: 'レザー ミニマルウォレット',
    category: 'Accessories',
    price: 26000,
    description: '無駄な装飾を削ぎ落とした、上質なレザーを使用したミニマルな二つ折りウォレット。',
    colors: ['Black', 'Brown'],
    sizes: ['Free'],
    images: ['ph-3', 'ph-1'],
  },
  {
    id: 'p14',
    name: 'シルク混 ロングスカーフ',
    category: 'Accessories',
    price: 18000,
    description: 'シルクを混紡した柔らかな落ち感の、一枚で装いを引き締めるロングスカーフ。',
    colors: ['Black', 'Greige', 'Ivory'],
    sizes: ['Free'],
    images: ['ph-1', 'ph-2'],
  },
];

window.TacetProducts = {
  getById(id) {
    return window.TACET_PRODUCTS.find((p) => p.id === id);
  },
  getByCategory(category) {
    if (!category || category === 'All') return window.TACET_PRODUCTS;
    return window.TACET_PRODUCTS.filter((p) => p.category === category);
  },
};
